<a href="https://colab.research.google.com/github/tasdemirgokhan/actions-learning-pathway/blob/main/diploma_2025_september.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x= 4.5
type(x)

float

In [ ]:
y=3567
type(y)

int

In [ ]:
x=4.5
x=int(x)
print(x)
type(x)

4


int

When converting floats to integers using int(), Python truncates the
decimal part (doesn't round)

Numbers without a decimal point are automatically stored as
integers

In [ ]:
z= "Welcome Python Ready Reckoner"
type(z)

str

In [ ]:
x="4.5"
type(x)

str

A character object is used to represent strings. A string is specified by using quotes (both single and double quotes will work).

In [ ]:
import pandas as pd

x = pd.Series(["high", "medium", "low", "low", "medium",

"high", "high", "high", "medium", "low", "low"])

x=pd.Categorical(x)

x.dtype

x.unique()

['high', 'medium', 'low']
Categories (3, object): ['high', 'low', 'medium']

**A Categorical** type is for a categorical variable that can take only one of a fixed, finite set of possibilities. These possible categories are called levels.

In [ ]:
#Here display shows the categories of the x.
x=pd.Categorical(x,categories=["low","medium","high"])
display(x)





['high', 'medium', 'low', 'low', 'medium', ..., 'high', 'high', 'medium', 'low', 'low']
Length: 11
Categories (3, object): ['low', 'medium', 'high']

In [ ]:
x=4.5
isinstance(x,int)

y=4
z=7
isinstance(bool,bool)


False

Logical type objects can only take 2 values: TRUE or FALSE (Boolean values)

**isinstance()** returns true if the object argument is an instance of the
class info argument.




In [ ]:
import numpy as np
a = [1,2,3,4,5,6]
print(a)
b=["one","two","three","four","five","six"]
print(b)
d=np.array([4,3,255,69,7,89,])
d>5



[1, 2, 3, 4, 5, 6]
['one', 'two', 'three', 'four', 'five', 'six']


array([False, False,  True,  True,  True,  True])

**np.array()** creates an array with one or multiple dimensions

np.array() function is used to create a matrix **(multidimensional array).**

**reshape(rows,cols)** is used to specify the dimensions of the matrix. Note
that the matrix is filled in row-wise in Python.


In [ ]:
np.array([2,3,4,5,6,7]).reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x=pd.DataFrame(np.array([2,3,4,5,6,7]).reshape(3,2),
index=["X","Y","Z"],columns=["A","B"])
display(x)

A  B
X  2  3
Y  4  5
Z  6  7

NOTE= in pandas, when you create a DataFrame, the parameter to specify the row labels is called index, not rows. The DataFrame constructor expects the argument name index to assign the row labels. Using rows will result in a TypeError because it's not a recognized parameter name for the DataFrame constructor.



In [ ]:
x=pd.DataFrame(np.array([2,3,4,5,6,7]).reshape(3,2),
index=["X","Y","Z"],columns=["A","B"])


# Output: Index(['A', 'B'], dtype='object')

x.rename(columns={'A':'a', 'B':'b'}), (x.rename(index={"X":"x","Y":"y","Z":"z"},inplace=True))
x.columns

display(x)

A  B
x  2  3
y  4  5
z  6  7

In [ ]:
A=np.arange(1,25).reshape(4,3,2)
display(a)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])